name: Continues Integration

on:
  push:
  pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2
        with:
            fetch-origin: 0
      - name: Use Node.js
        uses: action/setup-node@v2
        with: 
          node-version: '18.x'
      - name: Install Deps
        run: npm install

      - name: Run linters
        run: npm run lint


